-- Generated from generator/demo_specs/aws-vietnam-textile-order.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-textile-order
-- This is the schema that is actually deployed for VIETNAM_TEXTILE_ORDER.

-- Alerts fire on the bottom tail of On-Time Delivery
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ON_TIME_DELIVERY) AS T
  FROM RAW.CUSTOMER_ORDERS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ON_TIME_DELIVERY <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY,
  ROUND(AVG(f.KPI_CUSTOMERS), 2) AS AVG_CUSTOMERS,
  ROUND(AVG(f.KPI_AVG_LEAD_TIME), 2) AS AVG_LEAD_TIME,
  ROUND(AVG(f.KPI_FILL_RATE), 2) AS AVG_FILL_RATE,
  ROUND(AVG(f.KPI_CANCELLATION_RATE), 2) AS AVG_CANCELLATION_RATE
FROM RAW.CUSTOMER_ORDERS f
JOIN RAW.FACTORIES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ON_TIME_DELIVERY), 2) AS AVG_ON_TIME_DELIVERY,
  ROUND(AVG(f.KPI_CUSTOMERS), 2) AS AVG_CUSTOMERS,
  ROUND(AVG(f.KPI_AVG_LEAD_TIME), 2) AS AVG_LEAD_TIME,
  ROUND(AVG(f.KPI_FILL_RATE), 2) AS AVG_FILL_RATE,
  ROUND(AVG(f.KPI_CANCELLATION_RATE), 2) AS AVG_CANCELLATION_RATE
FROM RAW.CUSTOMER_ORDERS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ON_TIME_DELIVERY) AS KPI_ON_TIME_DELIVERY, AVG(KPI_CUSTOMERS) AS KPI_CUSTOMERS, AVG(KPI_AVG_LEAD_TIME) AS KPI_AVG_LEAD_TIME, AVG(KPI_FILL_RATE) AS KPI_FILL_RATE, AVG(KPI_CANCELLATION_RATE) AS KPI_CANCELLATION_RATE FROM RAW.CUSTOMER_ORDERS),
     en AS (SELECT SUM(KPI_ORDER_BOOK_VALUE) AS KPI_ORDER_BOOK_VALUE, SUM(KPI_ACTIVE_ORDERS) AS KPI_ACTIVE_ORDERS FROM RAW.FACTORIES)
  SELECT 1 AS SORT_ORDER, 'Order Book Value' AS TITLE, KPI_ORDER_BOOK_VALUE AS VALUE_NUM, '₫' || TO_VARCHAR(CAST(ROUND(((KPI_ORDER_BOOK_VALUE) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'On-Time Delivery' AS TITLE, KPI_ON_TIME_DELIVERY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ON_TIME_DELIVERY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Active Orders' AS TITLE, KPI_ACTIVE_ORDERS AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_ORDERS)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Customers' AS TITLE, KPI_CUSTOMERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CUSTOMERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Avg Lead Time' AS TITLE, KPI_AVG_LEAD_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AVG_LEAD_TIME)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Fill Rate' AS TITLE, KPI_FILL_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FILL_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Cancellation Rate' AS TITLE, KPI_CANCELLATION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CANCELLATION_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
